# Generated by Django 4.0.2 on 2022-03-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_businessdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetailsmodel',
            name='ids',
            field=models.CharField(default=1, max_length=240),
            preserve_default=False,
        ),
    ]
