# Generated by Django 4.0.2 on 2022-03-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_businessdetailsmodel_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessDetailsModel',
        ),
    ]
