# Generated by Django 4.0.2 on 2022-03-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_businessdetailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
