# Generated by Django 4.0.2 on 2022-03-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_restaurantmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantModels',
        ),
    ]
