# Generated by Django 4.0.2 on 2022-04-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='my_date',
            new_name='date',
        ),
    ]
