# Generated by Django 4.0.2 on 2022-04-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_plan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('La Salles', 'La Salles'), ('B Street Public House', 'B Street Public House'), ('Parkside Tap House', 'Parkside Tap House'), ('The Allies Pub', 'The Allies Pub'), ('Momona', 'Momona'), ('The Banshee', 'The Banshee'), ('Fresh Twisted Cafe', 'Fresh Twisted Cafe'), ('Taps Bar and Grill', 'Taps Bar and Grill'), ('Ali Baba', 'Ali Baba'), ('Sicilian Cafe', 'Sicilian Cafe'), ("Spiteri's Delicatessen", "Spiteri's Delicatessen"), ('Burban Kitchen', 'Burban Kitchen'), ('Tres Hombres Long Bar and Grill', 'Tres Hombres Long Bar and Grill'), ('Sierra Nevada Taproom & Restaurant', 'Sierra Nevada Taproom & Restaurant'), ('Burgers and Brew', 'Burgers and Brew'), ("Mom's Restaurant", "Mom's Restaurant"), ('The Handle Bar', 'The Handle Bar'), ('Ojiya Japanese Steakhouse and Sushi Bar', 'Ojiya Japanese Steakhouse and Sushi Bar'), ('Red Tavern', 'Red Tavern'), ('Big Hot Crab', 'Big Hot Crab')], default=1, max_length=240),
            preserve_default=False,
        ),
    ]
