# Generated by Django 4.0.2 on 2022-05-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('La Salles', 'La Salles'), ('Fresh Twisted Cafe', 'Fresh Twisted Cafe'), ('B Street Public House', 'B Street Public House'), ('The Allies Pub', 'The Allies Pub'), ('Momona', 'Momona'), ('The Banshee', 'The Banshee'), ('Parkside Tap House', 'Parkside Tap House'), ('Ali Baba', 'Ali Baba'), ("Spiteri's Delicatessen", "Spiteri's Delicatessen"), ('Sicilian Cafe', 'Sicilian Cafe'), ('Taps Bar and Grill', 'Taps Bar and Grill'), ('Burgers and Brew', 'Burgers and Brew'), ('The Handle Bar', 'The Handle Bar'), ('Sierra Nevada Taproom & Restaurant', 'Sierra Nevada Taproom & Restaurant'), ('Burban Kitchen', 'Burban Kitchen'), ('Tres Hombres Long Bar and Grill', 'Tres Hombres Long Bar and Grill'), ('Ojiya Japanese Steakhouse and Sushi Bar', 'Ojiya Japanese Steakhouse and Sushi Bar'), ('Broadway Heights', 'Broadway Heights'), ('Red Tavern', 'Red Tavern'), ("Mom's Restaurant", "Mom's Restaurant")], max_length=240),
        ),
    ]
