# Generated by Django 4.0.2 on 2022-05-02 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_plan_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 5, 2, 23, 31, 8, 991542, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('La Salles', 'La Salles'), ('Fresh Twisted Cafe', 'Fresh Twisted Cafe'), ('B Street Public House', 'B Street Public House'), ('The Allies Pub', 'The Allies Pub'), ('Momona', 'Momona'), ('The Banshee', 'The Banshee'), ('Parkside Tap House', 'Parkside Tap House'), ('Ali Baba', 'Ali Baba'), ('Sicilian Cafe', 'Sicilian Cafe'), ('Taps Bar and Grill', 'Taps Bar and Grill'), ('Burgers and Brew', 'Burgers and Brew'), ('The Handle Bar', 'The Handle Bar'), ('Sierra Nevada Taproom & Restaurant', 'Sierra Nevada Taproom & Restaurant'), ("Spiteri's Delicatessen", "Spiteri's Delicatessen"), ('Burban Kitchen', 'Burban Kitchen'), ('Tres Hombres Long Bar and Grill', 'Tres Hombres Long Bar and Grill'), ('Red Tavern', 'Red Tavern'), ('Ojiya Japanese Steakhouse and Sushi Bar', 'Ojiya Japanese Steakhouse and Sushi Bar'), ('Broadway Heights', 'Broadway Heights'), ("Mom's Restaurant", "Mom's Restaurant")], max_length=240),
        ),
    ]
