# Generated by Django 4.0.2 on 2022-05-03 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_plan_attendees_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2022, 5, 3, 22, 23, 1, 206699, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2022, 5, 3, 22, 23, 11, 263536, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
