# Generated by Django 4.0.2 on 2022-05-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rename_user_profile_user_n_alter_plan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_n',
            new_name='user',
        ),
    ]
