# Generated by Django 4.0.2 on 2022-05-18 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0037_alter_plan_name_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('La Salles', 'La Salles'), ('Parkside Tap House', 'Parkside Tap House'), ('B Street Public House', 'B Street Public House'), ('The Allies Pub', 'The Allies Pub'), ('Taps Bar and Grill', 'Taps Bar and Grill'), ('Momona', 'Momona'), ('The Banshee', 'The Banshee'), ('Fresh Twisted Cafe', 'Fresh Twisted Cafe'), ('Sicilian Cafe', 'Sicilian Cafe'), ('Ali Baba', 'Ali Baba'), ("Spiteri's Delicatessen", "Spiteri's Delicatessen"), ('Tres Hombres Long Bar and Grill', 'Tres Hombres Long Bar and Grill'), ('Burban Kitchen', 'Burban Kitchen'), ('Sierra Nevada Taproom & Restaurant', 'Sierra Nevada Taproom & Restaurant'), ('Burgers and Brew', 'Burgers and Brew'), ('The Handle Bar', 'The Handle Bar'), ('Ojiya Japanese Steakhouse and Sushi Bar', 'Ojiya Japanese Steakhouse and Sushi Bar'), ('Red Tavern', 'Red Tavern'), ("Mom's Restaurant", "Mom's Restaurant"), ('Main Street Pizza', 'Main Street Pizza')], max_length=240),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
