# Generated by Django 4.0.2 on 2022-05-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('La Salles', 'La Salles'), ('B Street Public House', 'B Street Public House'), ('The Allies Pub', 'The Allies Pub'), ('Momona', 'Momona'), ('The Banshee', 'The Banshee'), ('Fresh Twisted Cafe', 'Fresh Twisted Cafe'), ('Parkside Tap House', 'Parkside Tap House'), ('Sicilian Cafe', 'Sicilian Cafe'), ('Taps Bar and Grill', 'Taps Bar and Grill'), ('Ali Baba', 'Ali Baba'), ("Spiteri's Delicatessen", "Spiteri's Delicatessen"), ('Tres Hombres Long Bar and Grill', 'Tres Hombres Long Bar and Grill'), ('Burban Kitchen', 'Burban Kitchen'), ('Sierra Nevada Taproom & Restaurant', 'Sierra Nevada Taproom & Restaurant'), ('Burgers and Brew', 'Burgers and Brew'), ('The Handle Bar', 'The Handle Bar'), ('Ojiya Japanese Steakhouse and Sushi Bar', 'Ojiya Japanese Steakhouse and Sushi Bar'), ("Mom's Restaurant", "Mom's Restaurant"), ('Red Tavern', 'Red Tavern'), ('Main Street Pizza', 'Main Street Pizza')], max_length=240),
        ),
    ]
